# Yaml for api-jva-motor-fees (RESTful)
---
swagger: "2.0"
info:
  title: Swagger Spec For Motor fees REST API
  description: This is the specification for the Motor fees REST API
  version: "1.0"
  termsOfService: http://localhost/terms-and-conditions
  contact:
    name: API Factory Team
    url: http://www.esure.com
    email: api-dev@esure.com
  license:
    name: Company Licence
    url: http://www.esure.com/licenses/LICENSE-2.0.html
host: localhost:9690
basePath: /v1
consumes:
- application/json
produces:
- application/json
paths:
  /fees/admin/calculate:
    post:
      tags:
      - motorFees
      summary:
      description: ""
      operationId: calculateAdminFee
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/MotorFeesRequest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MotorFeesResponse'
        '201':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Failure

definitions:
  MotorFeesRequest:
    type: object
    properties:
      policyNo:
        type: string
        pattern: "^[0-9]{1,10}$"
      version:
        type: string
        default: IN-FORCE
        pattern: "^(LATEST)|(latest)|(IN-FORCE)|(in-force)|([0-9]{1,10})$"
      mtaTransactionTypes:
        type: array
        items:
          type: string
    required:
    - policyNo

  MotorFeesResponse:
    type: object
    allOf:
    - $ref: './common.yaml#/ResponseWrapper'
    - properties:
        results:
          type: array
          items:
            $ref: '#/definitions/FeesResponse'

  FeesResponse:
    type: object
    properties:
      policyNo:
        type: string
        pattern: "^[0-9]{1,10}$"
      version:
        type: string
        default: IN-FORCE
        pattern: "^(LATEST)|(latest)|(IN-FORCE)|(in-force)|([0-9]{1,10})$"
      mtaTransactionTypes:
        type: array
        items:
          type: string
    required:
    - policyNo